from odoo import models, fields

class CashflowControllerBI(models.Model):
    _name = 'cashflow.controller.bi'
    _description = 'Cashflow Controller BI'

    cashflow_bi_id = fields.Integer(string="Cashflow BI ID")
    cashflow_id = fields.Integer(string="Cashflow ID")
    trade_number = fields.Integer(string="Trade Number")
    term_number = fields.Integer(string="Term Number")
    section_no = fields.Char(string="Section No")
    external_reference = fields.Char(string="External Reference")
    internal_reference = fields.Char(string="Internal Reference")
    exchange_id = fields.Char(string="Exchange ID")
    broker_ref = fields.Char(string="Broker Reference")
    strategy = fields.Char(string="Strategy")
    counterpart = fields.Char(string="Counterpart")
    internal_company = fields.Char(string="Internal Company")
    underlying_start = fields.Datetime(string="Underlying Start")
    underlying_end = fields.Datetime(string="Underlying End")
    payment_due_date = fields.Datetime(string="Payment Due Date")
    quantity = fields.Float(string="Quantity")
    quantity_uom = fields.Char(string="Quantity UOM")
    price = fields.Float(string="Price")
    price_currency = fields.Char(string="Price Currency")
    price_uom = fields.Char(string="Price UOM")
    extended_amount = fields.Float(string="Extended Amount")
    commodity = fields.Char(string="Commodity")
    trade_type = fields.Char(string="Trade Type")
    cost_type = fields.Char(string="Cost Type")
    cashflow_status = fields.Char(string="Cashflow Status")
    trade_pricing_status = fields.Char(string="Trade Pricing Status")
    price_entry_start_date = fields.Datetime(string="Price Entry Start Date")
    price_entry_end_date = fields.Datetime(string="Price Entry End Date")
    pricing_quote = fields.Char(string="Pricing Quote")
    price1 = fields.Float(string="Price 1")
    location = fields.Char(string="Location")
    quantity_status = fields.Char(string="Quantity Status")
    buy_sell = fields.Char(string="Buy/Sell")
    venture = fields.Char(string="Venture")
    payment_status = fields.Char(string="Payment Status")
    invoice_number = fields.Integer(string="Invoice Number")
    item_invoiced = fields.Char(string="Item Invoiced")
    financial_credit_instrument = fields.Char(string="Financial Credit Instrument")
    delivery_ref = fields.Char(string="Delivery Reference")
    delivery_type = fields.Char(string="Delivery Type")
    transfer_number = fields.Integer(string="Transfer Number")
    actual_estimate = fields.Char(string="Actual Estimate")
    effective_date = fields.Datetime(string="Effective Date")
    act_period = fields.Char(string="Activity Period")
    bl_date = fields.Datetime(string="BL Date")
    incoterm = fields.Char(string="Incoterm")
    prem_desc = fields.Float(string="Premium Description")
    trader_person = fields.Char(string="Trader Person")
    segment_price_entry_id = fields.Integer(string="Segment Price Entry ID")
    cost_revenue = fields.Char(string="Cost Revenue")
    pricing_type = fields.Char(string="Pricing Type")
    price_category = fields.Char(string="Price Category")
    payable_receivable = fields.Char(string="Payable/Receivable")
    strategy_cost_number = fields.Integer(string="Strategy Cost Number")
    external_cost_category = fields.Char(string="External Cost Category")
    internal_cost_category = fields.Char(string="Internal Cost Category")
    bu_company = fields.Char(string="BU Company")
    quality_spec_type = fields.Char(string="Quality Spec Type")
    logistic_contract_number = fields.Integer(string="Logistic Contract Number")
    load_location = fields.Char(string="Load Location")
    discharge_location_1 = fields.Char(string="Discharge Location 1")
    final_destination = fields.Char(string="Final Destination")
    price2 = fields.Float(string="Price 2")
    contract_qty = fields.Float(string="Contract Quantity")
    contract_qty_uom = fields.Char(string="Contract Quantity UOM")
    load_bl_quantity = fields.Float(string="Load BL Quantity")
    load_qty_uom = fields.Char(string="Load Quantity UOM")
    discharge_qty1 = fields.Float(string="Discharge Quantity 1")
    discharge_qty_uom1 = fields.Char(string="Discharge Quantity UOM 1")
    nor_date1 = fields.Datetime(string="NOR Date 1")
    trading_route = fields.Char(string="Trading Route")
    discharge2_qty = fields.Float(string="Discharge Quantity 2")
    discharge2_qty_uom = fields.Char(string="Discharge Quantity UOM 2")
    nor_date2 = fields.Datetime(string="NOR Date 2")
    discharge2_location_code = fields.Char(string="Discharge Location Code 2")
    cost_discription = fields.Char(string="Cost Description")
    final_quantity = fields.Float(string="Final Quantity")
    final_quantity_uom = fields.Char(string="Final Quantity UOM")
    exchange_contract = fields.Char(string="Exchange Contract")
    execution_broker = fields.Char(string="Execution Broker")
    market_exchange = fields.Char(string="Market Exchange")
    storage = fields.Char(string="Storage")
    level = fields.Char(string="Level")
    retrieve_date = fields.Datetime(string="Retrieve Date")
    trade_date = fields.Datetime(string="Trade Date")
    link_number = fields.Integer(string="Link Number")
    shape = fields.Char(string="Shape")
    brand = fields.Char(string="Brand")
    origin = fields.Char(string="Origin")
    formula_expression = fields.Char(string="Formula Expression")
    delivery_reference = fields.Char(string="Delivery Reference")
    trailer_number = fields.Char(string="Trailer Number")
    package_count = fields.Integer(string="Package Count")
    shape_code = fields.Char(string="Shape Code")
    seg_lot_reference = fields.Char(string="Seg Lot Reference")
    book = fields.Char(string="Book")
    prompt_date = fields.Datetime(string="Prompt Date")
    original_extended_amt = fields.Float(string="Original Extended Amount")
    cost_group = fields.Integer(string="Cost Group")
    concentrate_type = fields.Integer(string="Concentrate Type")
    title_transfer_date = fields.Datetime(string="Title Transfer Date")
    allocation_number = fields.Integer(string="Allocation Number")
    is_split_cashflow = fields.Char(string="Is Split Cashflow")
    source_cashflow_number = fields.Integer(string="Source Cashflow Number")
    cost_percentage = fields.Float(string="Cost Percentage")
    franchise_percentage = fields.Float(string="Franchise Percentage")
    payment_date = fields.Datetime(string="Payment Date")
    payment_description = fields.Char(string="Payment Description")
    logistic_type = fields.Integer(string="Logistic Type")
    itinerary_id = fields.Integer(string="Itinerary ID")
    front_back_leg = fields.Char(string="Front/Back Leg")
    storage_cost_type = fields.Char(string="Storage Cost Type")
    storage_cost_number = fields.Integer(string="Storage Cost Number")
    business_unit = fields.Char(string="Business Unit")
    portfolio_segment = fields.Char(string="Portfolio Segment")
    optional_section = fields.Char(string="Optional Section")
    declaration_date = fields.Datetime(string="Declaration Date")
    trade_admin = fields.Char(string="Trade Admin")
    operator_person = fields.Char(string="Operator Person")
    valuation_category = fields.Char(string="Valuation Category")
    material = fields.Char(string="Material")
    trade_status = fields.Char(string="Trade Status")
    material_type = fields.Char(string="Material Type")
    link_type = fields.Char(string="Link Type")
    commencement_date = fields.Datetime(string="Commencement Date")
    document_receipt_date = fields.Datetime(string="Document Receipt Date")
    bill_to_party = fields.Char(string="Bill to Party")
    payer = fields.Char(string="Payer")
    ship_to_party = fields.Char(string="Ship to Party")
    invoice_presented_by = fields.Char(string="Invoice Presented By")
    proforma = fields.Char(string="Proforma")
    not_for_own_use = fields.Char(string="Not for Own Use")
    embedded_derivative = fields.Char(string="Embedded Derivative")
    adjusted_due_date = fields.Datetime(string="Adjusted Due Date")
    original_quantity = fields.Float(string="Original Quantity")
    parent_link_trade_id = fields.Integer(string="Parent Link Trade ID")
    internal_strategy = fields.Char(string="Internal Strategy")
    internal_portfolio = fields.Char(string="Internal Portfolio")
    internal_storage = fields.Char(string="Internal Storage")
    financially_settled = fields.Char(string="Financially Settled")
    planning_quantity = fields.Float(string="Planning Quantity")
    shipping_quantity = fields.Float(string="Shipping Quantity")
    planning_uom = fields.Char(string="Planning UOM")
    shipping_uom = fields.Char(string="Shipping UOM")
    zero_out_qty = fields.Float(string="Zero Out Quantity")
    implicit_cost = fields.Char(string="Implicit Cost")
    financing_bank = fields.Char(string="Financing Bank")
    finance_reference = fields.Char(string="Finance Reference")
    leg_type = fields.Char(string="Leg Type")
    efp = fields.Char(string="EFP")
    efp_physical = fields.Integer(string="EFP Physical")
    efp_trigger_lot = fields.Integer(string="EFP Trigger Lot")
    voyage_segment = fields.Char(string="Voyage Segment")
    nomination_status = fields.Char(string="Nomination Status")
    pool = fields.Char(string="Pool")
    park_and_loan = fields.Char(string="Park and Loan")
    financial_match_number = fields.Integer(string="Financial Match Number")
    native_trade_price = fields.Float(string="Native Trade Price")
    native_trade_price_currency = fields.Char(string="Native Trade Price Currency")
    native_trade_price_uom = fields.Char(string="Native Trade Price UOM")
    processing_number = fields.Integer(string="Processing Number")
    invoice_date = fields.Datetime(string="Invoice Date")
    grade = fields.Char(string="Grade")
    master_deal_id = fields.Integer(string="Master Deal ID")
    trade_sub_status = fields.Char(string="Trade Sub Status")
    qp_final = fields.Char(string="QP Final")
    delivery_reference_2 = fields.Char(string="Delivery Reference 2")
    delivery_reference_3 = fields.Char(string="Delivery Reference 3")
    delivery_reference_4 = fields.Char(string="Delivery Reference 4")
    delivery_reference_5 = fields.Char(string="Delivery Reference 5")
    nomination_key = fields.Integer(string="Nomination Key")
    extended_amt_sys_base_ccy = fields.Float(string="Extended Amount System Base CCY")
    ext_amt_base_currency = fields.Float(string="Extended Amount Base Currency")
    ic_base_currency = fields.Char(string="IC Base Currency")
    ext_amt_rpt_currency = fields.Float(string="Extended Amount Report Currency")
    ic_rpt_currency = fields.Char(string="IC Report Currency")
    stl_to_system_base_fx_rate = fields.Float(string="STL to System Base FX Rate")
    stl_to_ic_base_fx_rate = fields.Float(string="STL to IC Base FX Rate")
    stl_to_ic_rpt_fx_rate = fields.Float(string="STL to IC Report FX Rate")
    event_date = fields.Datetime(string="Event Date")
    billing_address = fields.Char(string="Billing Address")
    mailing_address = fields.Char(string="Mailing Address")
    shipping_address = fields.Char(string="Shipping Address")
    master_deal_ref_number = fields.Char(string="Master Deal Ref Number")
    market_snapshot = fields.Char(string="Market Snapshot")
    internal_business_unit = fields.Char(string="Internal Business Unit")
    int_payment_instruction = fields.Char(string="INT Payment Instruction")
    company_sector = fields.Char(string="Company Sector")
    pledged_to_bank = fields.Char(string="Pledged to Bank")
    contract_size = fields.Char(string="Contract Size")
    accounting_period = fields.Char(string="Accounting Period")
    production_period = fields.Char(string="Production Period")
    tax_number = fields.Char(string="Tax Number")
    erp_tax_code = fields.Char(string="ERP Tax Code")
    surcharge_discount = fields.Integer(string="Surcharge Discount")
    tax_effective_from_date = fields.Datetime(string="Tax Effective From Date")
    tax_effective_to_date = fields.Datetime(string="Tax Effective To Date")
    cpty_level_instrument = fields.Char(string="Cpty Level Instrument")
    ticket_number = fields.Integer(string="Ticket Number")
    ticket_reference_1 = fields.Char(string="Ticket Reference 1")
    ticket_reference_2 = fields.Char(string="Ticket Reference 2")
    ticket_reference_3 = fields.Char(string="Ticket Reference 3")
    is_fully_ticketed = fields.Char(string="Is Fully Ticketed")
    driver_name = fields.Char(string="Driver Name")
    driver_id = fields.Char(string="Driver ID")
    folio_account = fields.Char(string="Folio Account")
    folio_account_number = fields.Char(string="Folio Account Number")
    transporter = fields.Integer(string="Transporter")
    registration_no = fields.Char(string="Registration No")
    bl_number = fields.Char(string="BL Number")
    trade_input_date = fields.Datetime(string="Trade Input Date")
    trigger_expiry = fields.Datetime(string="Trigger Expiry")
    imported = fields.Char(string="Imported")
    alternate_payer = fields.Char(string="Alternate Payer")
    section_type = fields.Char(string="Section Type")
    transfer_completion_date = fields.Datetime(string="Transfer Completion Date")
    parent_invoice = fields.Integer(string="Parent Invoice")
    match_number = fields.Integer(string="Match Number")
    reach_category = fields.Char(string="Reach Category")
    bonded_nonbonded = fields.Char(string="Bonded/Nonbonded")
    trade_last_modified_date = fields.Datetime(string="Trade Last Modified Date")
    transfer_created_by = fields.Char(string="Transfer Created By")
    commodity_group1 = fields.Char(string="Commodity Group 1")
    commodity_group2 = fields.Char(string="Commodity Group 2")
    cost_external_category = fields.Integer(string="Cost External Category")
    cost_internal_category = fields.Integer(string="Cost Internal Category")
    exch_contract_type = fields.Char(string="Exchange Contract Type")
    pass_through_cost = fields.Char(string="Pass Through Cost")
    delivery_period = fields.Datetime(string="Delivery Period")
    cert_effective_date = fields.Datetime(string="Certificate Effective Date")
    cert_expiry_date = fields.Datetime(string="Certificate Expiry Date")
    mot_type = fields.Char(string="MOT Type")
    actual_extended_amount = fields.Float(string="Actual Extended Amount")
    cleared = fields.Char(string="Cleared")
    custom_invoice_number = fields.Char(string="Custom Invoice Number")
    delivery_start_date = fields.Datetime(string="Delivery Start Date")
    delivery_end_date = fields.Datetime(string="Delivery End Date")
    estimated_extended_amount = fields.Float(string="Estimated Extended Amount")
    stp_trade = fields.Char(string="STP Trade")
    inter_company = fields.Char(string="Inter Company")
    license = fields.Char(string="License")
    location_bs_option = fields.Char(string="Location BS Option")
    mtm_pricing_type = fields.Char(string="MTM Pricing Type")
    nom_trans_type = fields.Char(string="Nom Trans Type")
    packaging = fields.Char(string="Packaging")
    parent_location = fields.Char(string="Parent Location")
    pass_through = fields.Char(string="Pass Through")
    payment_term = fields.Char(string="Payment Term")
    repo_type = fields.Char(string="Repo Type")
    settlement_ccy = fields.Char(string="Settlement CCY")
    settlement_uom = fields.Char(string="Settlement UOM")
    specification = fields.Char(string="Specification")
    tolerance_type_enum = fields.Integer(string="Tolerance Type Enum")
    trade_price_on = fields.Char(string="Trade Price On")
    company_agreement_type_name = fields.Char(string="Company Agreement Type Name")
    contact_person = fields.Char(string="Contact Person")
    calculated_demurrage = fields.Float(string="Calculated Demurrage")
    freight_delivery = fields.Integer(string="Freight Delivery")
    initial_claim = fields.Float(string="Initial Claim")
    lot = fields.Float(string="Lot")
    strategy_l1 = fields.Char(string="Strategy L1")
    strategy_l2 = fields.Char(string="Strategy L2")
    strategy_l3 = fields.Char(string="Strategy L3")
    strategy_l4 = fields.Char(string="Strategy L4")
    strategy_l5 = fields.Char(string="Strategy L5")
    total_demurrage_hours = fields.Char(string="Total Demurrage Hours")
    vehicle = fields.Char(string="Vehicle")
    cost_center = fields.Char(string="Cost Center")
    company_code = fields.Char(string="Company Code")
    gl_contract_type = fields.Char(string="GL Contract Type")
    ic_parent = fields.Char(string="IC Parent")
    lot_size = fields.Float(string="Lot Size")
    match_type = fields.Char(string="Match Type")
    prior_invoice_number = fields.Integer(string="Prior Invoice Number")
    profit_center = fields.Char(string="Profit Center")
    tc_contract_number = fields.Integer(string="TC Contract Number")
    cost_allocation = fields.Char(string="Cost Allocation")
    future_trade_type = fields.Char(string="Future Trade Type")
    portfolio = fields.Char(string="Portfolio")
    tax_code = fields.Char(string="Tax Code")
    parent_cashflow_id = fields.Integer(string="Parent Cashflow ID")
    hazardous = fields.Char(string="Hazardous")
    coa_check = fields.Char(string="COA Check")
    animal_feed = fields.Char(string="Animal Feed")
    reach = fields.Char(string="REACH")
    reach_registration_no = fields.Char(string="REACH Registration No")
    un_number = fields.Char(string="UN Number")
    un_packaging = fields.Char(string="UN Packaging")
    shelf_life_in_years = fields.Float(string="Shelf Life in Years")
    customer = fields.Char(string="Customer")
    service_provider = fields.Char(string="Service Provider")
    producer_manufacturing = fields.Char(string="Producer Manufacturing")
    repacker_tollerer = fields.Char(string="Repacker Tollerer")
    vendor = fields.Char(string="Vendor")
    other = fields.Char(string="Other")
    hs_code_type = fields.Char(string="HS Code Type")
    hs_code_general_6 = fields.Char(string="HS Code General 6")
    hs_code_local_4 = fields.Char(string="HS Code Local 4")
    hs_code_total_10 = fields.Char(string="HS Code Total 10")
    tax_jurisdiction = fields.Char(string="Tax Jurisdiction")
    from_jurisdiction = fields.Char(string="From Jurisdiction")
    to_jurisdiction = fields.Char(string="To Jurisdiction")
    ticket_reference_4 = fields.Char(string="Ticket Reference 4")
    ticket_reference_5 = fields.Char(string="Ticket Reference 5")
    production_period_date = fields.Datetime(string="Production Period Date")
    link_group_name = fields.Char(string="Link Group Name")
    broker_account = fields.Char(string="Broker Account")
    event_date_column1 = fields.Datetime(string="Event Date Column 1")
    event_date_column2 = fields.Datetime(string="Event Date Column 2")
    event_date_column3 = fields.Datetime(string="Event Date Column 3")
    event_date_column4 = fields.Datetime(string="Event Date Column 4")
    event_date_column5 = fields.Datetime(string="Event Date Column 5")
    event_date_column6 = fields.Datetime(string="Event Date Column 6")
    event_date_column7 = fields.Datetime(string="Event Date Column 7")
    event_date_column8 = fields.Datetime(string="Event Date Column 8")
    event_date_column9 = fields.Datetime(string="Event Date Column 9")
    event_date_column10 = fields.Datetime(string="Event Date Column 10")
    crop_year = fields.Char(string="Crop Year")
    variety_code = fields.Char(string="Variety Code")
    bill_of_lading = fields.Datetime(string="Bill of Lading")
    title_transfer_location = fields.Char(string="Title Transfer Location")
    line_space = fields.Char(string="Line Space")
    mt_volume = fields.Float(string="MT Volume")
    stock_in_out_id = fields.Integer(string="Stock In/Out ID")
    car_initials = fields.Char(string="Car Initials")
    car_number = fields.Char(string="Car Number")
    bol_number = fields.Char(string="BOL Number")
    storage_type = fields.Integer(string="Storage Type")
    deal_classification = fields.Char(string="Deal Classification")
    description = fields.Char(string="Description")
    force_majeure = fields.Char(string="Force Majeure")
    override_cost_revenue = fields.Char(string="Override Cost Revenue")
    pipeline = fields.Char(string="Pipeline")
    period = fields.Char(string="Period")
    period_type = fields.Char(string="Period Type")
    debit_account = fields.Char(string="Debit Account")
    credit_account = fields.Char(string="Credit Account")
    is_gl_adjustment = fields.Char(string="Is GL Adjustment")
    net_volume = fields.Float(string="Net Volume")
    gross_volume = fields.Float(string="Gross Volume")
    product_code = fields.Char(string="Product Code")
    product_symbol = fields.Char(string="Product Symbol")
    lot_equivalent = fields.Float(string="Lot Equivalent")
    broker_account_type = fields.Char(string="Broker Account Type")
    financing_bank_account = fields.Char(string="Financing Bank Account")
    custom_section_number = fields.Char(string="Custom Section Number")
    custom_trade_number = fields.Char(string="Custom Trade Number")
    erp_customer_id = fields.Char(string="ERP Customer ID")
    erp_vendor_id = fields.Char(string="ERP Vendor ID")
    delivery_origin = fields.Char(string="Delivery Origin")
    carriage_name = fields.Char(string="Carriage Name")
    transport_carriage_type = fields.Char(string="Transport Carriage Type")
    last_modify_date = fields.Datetime(string="Last Modify Date")
    bi_record_creation_date = fields.Datetime(string="BI Record Creation Date")
