from odoo import models, fields

class NominationControllerBI(models.Model):
    _name = 'nomination.controller.bi'
    _description = 'Nomination Controller Business Intelligence'

    itinerary_id = fields.Integer(string='Itinerary ID', index=True, help="Primary identifier for the Itinerary")
    itinerary_name = fields.Char(string='Itinerary Name')
    itinerary_status_enum = fields.Char(string='Itinerary Status')
    movement_id = fields.Integer(string='Movement ID')
    mot_type_enum = fields.Char(string='MOT Type')
    mot_id = fields.Integer(string='MOT ID')
    mot_code = fields.Char(string='MOT Code')
    depart_location_code = fields.Char(string='Departure Location Code')
    arrive_location_code = fields.Char(string='Arrival Location Code')
    depart_date = fields.Datetime(string='Departure Date')
    arrive_date = fields.Datetime(string='Arrival Date')
    itinerary_type_enum = fields.Char(string='Itinerary Type')
    material_id = fields.Integer(string='Material ID')
    transport_carriage_type_enum = fields.Char(string='Transport Carriage Type')
    inter_comp_enum = fields.Boolean(string='Intercompany')
    nomination_number = fields.Char(string='Nomination Number')
    sap_document_id = fields.Char(string='SAP Document ID')
    sap_status_enum = fields.Char(string='SAP Status')
    nomination_key = fields.Integer(string='Nomination Key')
    is_finalized = fields.Boolean(string='Is Finalized')
    finalized_date = fields.Datetime(string='Finalized Date')
    is_finalized_movement = fields.Boolean(string='Is Finalized Movement')
    finalized_date_movement = fields.Datetime(string='Finalized Movement Date')
    sample_required_enum_display_text = fields.Char(string='Sample Required Display Text')
    sampling_process_code = fields.Char(string='Sampling Process Code')
    weight_final_at_display_text = fields.Char(string='Weight Final At Display Text')
    delivery_basis_of_display_text = fields.Char(string='Delivery Basis of Display Text')
    status_enum = fields.Boolean(string='Status')
    modify_person_id = fields.Integer(string='Modify Person ID')
    last_modify_date = fields.Datetime(string='Last Modify Date')
    modify_person = fields.Char(string='Modify Person')
    customer_id = fields.Integer(string='Customer ID')
    lock_id = fields.Integer(string='Lock ID')
    bi_record_creation_date = fields.Datetime(string='BI Record Creation Date')
