from odoo import models, fields


class TradeControllerBI(models.Model):
    _name = 'trade.controller.bi'
    _description = 'Trade Controller BI'
    
    deal_master_id = fields.Integer( string='Deal Master ID', index=True)
    segment_id = fields.Integer( string='Segment ID', index=True)
    external_ref = fields.Char(string='External Reference')
    trade_date = fields.Datetime(string='Trade Date')
    internal_company = fields.Char(string='Internal Company')
    counterpart_company = fields.Char(string='Counterpart Company')
    trader_person = fields.Char(string='Trader Person')
    segment_section_code = fields.Char(string='Segment Section Code')
    commodity = fields.Char(string='Commodity')
    delivery_term = fields.Char(string='Delivery Term')
    strategy = fields.Char(string='Strategy')
    location = fields.Char(string='Location')
    lot = fields.Float(string='Lot')
    lot_size = fields.Float(string='Lot Size')
    trade_qty = fields.Float(string='Trade Quantity')
    qty_uom = fields.Char(string='Quantity UOM')
    calendar = fields.Char(string='Calendar')
    start_date = fields.Datetime(string='Start Date')
    end_date = fields.Datetime(string='End Date')
    delivery_schedule = fields.Char(string='Delivery Schedule')
    settlement_currency = fields.Char(string='Settlement Currency')
    settlement_uom = fields.Char(string='Settlement UOM')
    settlement_payment_term = fields.Char(string='Settlement Payment Term')
    letter_of_credit = fields.Text(string='Letter of Credit')
    venture_code = fields.Char(string='Venture Code')
    logistic_contract_id = fields.Integer(  string='Logistic Contract ID', index=True)
    trade_link_id = fields.Char(string='Trade Link ID')
    trade_link_code = fields.Char(string='Trade Link Code')
    exchange_contract = fields.Char(string='Exchange Contract')
    exchange_ref = fields.Char(string='Exchange Reference')
    broker_ref = fields.Char(string='Broker Reference')
    broker2_company = fields.Char(string='Broker2 Company')
    exchange = fields.Char(string='Exchange')
    trade_price = fields.Char(string='Trade Price')
    price_currency = fields.Char(string='Price Currency')
    price_uom = fields.Char(string='Price UOM')
    commodity_group = fields.Char(string='Commodity Group')
    inter_comp_trade_number = fields.Integer(string='Inter Company Trade Number')
    stage_name = fields.Char(string='Stage Name')
    current_stage_name = fields.Char(string='Current Stage Name')
    load_location = fields.Char(string='Load Location')
    discharge_location = fields.Char(string='Discharge Location')
    account = fields.Char(string='Account')
    book = fields.Char(string='Book')
    brand = fields.Char(string='Brand')
    shape = fields.Char(string='Shape')
    udf1 = fields.Char(string='UDF1')
    udf2 = fields.Char(string='UDF2')
    udf3 = fields.Char(string='UDF3')
    udf4 = fields.Char(string='UDF4')
    udf5 = fields.Char(string='UDF5')
    udf6 = fields.Char(string='UDF6')
    udf7 = fields.Char(string='UDF7')
    udf8 = fields.Char(string='UDF8')
    udf9 = fields.Char(string='UDF9')
    udf10 = fields.Char(string='UDF10')
    grade = fields.Char(string='Grade')
    fund = fields.Char(string='Fund')
    origin = fields.Char(string='Origin')
    master_contract_id = fields.Integer(  string='Master Contract ID', index=True)
    segment_reference = fields.Char(string='Segment Reference')
    portfolio = fields.Char(string='Portfolio')
    total_allocated_qty = fields.Float(string='Total Allocated Quantity')
    open_allocated_qty = fields.Float(string='Open Allocated Quantity')
    concentrate_enum = fields.Integer(string='Concentrate Enum')
    qs_type = fields.Char(string='QS Type')
    financing_account = fields.Char(string='Financing Account')
    financing_transfer_date = fields.Datetime(string='Financing Transfer Date')
    customer_reference = fields.Char(string='Customer Reference')
    business_unit = fields.Char(string='Business Unit')
    portfolio_segment = fields.Char(string='Portfolio Segment')
    declaration_date = fields.Datetime(string='Declaration Date')
    optional_section_enum = fields.Integer(string='Optional Section Enum')
    trade_admin = fields.Char(string='Trade Admin')
    operator = fields.Char(string='Operator')
    material = fields.Char(string='Material')
    mot = fields.Char(string='MOT')
    master_deal_id = fields.Integer(  string='Master Deal ID', index=True)
    expiry_date = fields.Datetime(string='Expiry Date')
    link_type = fields.Char(string='Link Type')
    bill_to_party_counterpart = fields.Char(string='Bill to Party Counterpart')
    payer_counterpart = fields.Char(string='Payer Counterpart')
    ship_to_party_counterpart = fields.Char(string='Ship to Party Counterpart')
    invoice_presented_by_counterpart = fields.Char(string='Invoice Presented by Counterpart')
    inter_company_buy_id = fields.Integer(  string='Inter Company Buy ID', index=True)
    inter_company_sell_id = fields.Integer(  string='Inter Company Sell ID', index=True)
    intercompany_template_code = fields.Char(string='Intercompany Template Code')
    is_not_for_own_use = fields.Boolean(string='Is Not for Own Use')
    is_embedded_derivative = fields.Boolean(string='Is Embedded Derivative')
    deal_sheet_master_id = fields.Integer(  string='Deal Sheet Master ID', index=True)
    internal_storage = fields.Char(string='Internal Storage')
    internal_portfolio = fields.Char(string='Internal Portfolio')
    internal_strategy = fields.Char(string='Internal Strategy')
    planning_quantity = fields.Float(string='Planning Quantity')
    shipping_quantity = fields.Float(string='Shipping Quantity')
    planning_uom = fields.Char(string='Planning UOM')
    shipping_uom = fields.Char(string='Shipping UOM')
    is_financially_settled = fields.Boolean(string='Is Financially Settled')
    offer_sheet_mapped_to_deal = fields.Boolean(string='Offer Sheet Mapped to Deal')
    is_tas_trade = fields.Boolean(string='Is TAS Trade')
    quote_std_formula = fields.Char(string='Quote Standard Formula')
    expiration_date = fields.Datetime(string='Expiration Date')
    hourly_daily_qty = fields.Float(string='Hourly Daily Quantity')
    efp_deal_master_id = fields.Integer(  string='EFP Deal Master ID', index=True)
    voyage_segment_type_enum = fields.Integer(string='Voyage Segment Type Enum')
    is_park_and_loan = fields.Boolean(string='Is Park and Loan')
    is_pool = fields.Boolean(string='Is Pool')
    vessel_name = fields.Char(string='Vessel Name')
    trade_sub_status = fields.Char(string='Trade Sub Status')
    trade_type = fields.Char(string='Trade Type')
    pricing_type = fields.Char(string='Pricing Type')
    chartering_instrument_id = fields.Integer(  string='Chartering Instrument ID', index=True)
    financing_bank = fields.Char(string='Financing Bank')
    mailing_address = fields.Char(string='Mailing Address')
    shipping_address = fields.Char(string='Shipping Address')
    billing_address = fields.Char(string='Billing Address')
    reference_number = fields.Char(string='Reference Number')
    hs_code_type = fields.Char(string='HS Code Type')
    company_sector = fields.Char(string='Company Sector')
    internal_reference = fields.Char(string='Internal Reference')
    is_hazardous_enum = fields.Integer(string='Is Hazardous Enum')
    un_number = fields.Char(string='UN Number')
    un_packaging_code = fields.Char(string='UN Packaging Code')
    is_reach = fields.Boolean(string='Is REACH')
    reach_registration_no = fields.Char(string='REACH Registration No')
    shelf_life = fields.Float(string='Shelf Life')
    is_coa_check = fields.Boolean(string='Is COA Check')
    is_animal_feed = fields.Boolean(string='Is Animal Feed')
    is_vendor = fields.Boolean(string='Is Vendor')
    is_customer = fields.Boolean(string='Is Customer')
    is_service_provider = fields.Boolean(string='Is Service Provider')
    is_producer_manufacturing = fields.Boolean(string='Is Producer Manufacturing')
    is_repacker_tollerer = fields.Boolean(string='Is Repacker/Tollerer')
    is_other = fields.Boolean(string='Is Other')
    hs_code_general = fields.Char(string='HS Code General')
    hs_code_local = fields.Char(string='HS Code Local')
    hs_code_total = fields.Char(string='HS Code Total')
    commodity_group2 = fields.Char(string='Commodity Group 2')
    trade_input_date = fields.Datetime(string='Trade Input Date')
    trigger_expiration_date = fields.Datetime(string='Trigger Expiration Date')
    exch_contract_type = fields.Char(string='Exchange Contract Type')
    internal_reference1 = fields.Char(string='Internal Reference 1')
    security_id = fields.Char(string='Security ID')
    is_finalized = fields.Boolean(string='Is Finalized')
    is_time_spread = fields.Boolean(string='Is Time Spread')
    is_imported_trade = fields.Boolean(string='Is Imported Trade')
    section_type_enum = fields.Integer(string='Section Type Enum')
    finalized_date = fields.Datetime(string='Finalized Date')
    trade_last_modified_date = fields.Datetime(string='Trade Last Modified Date')
    is_structured_deal = fields.Boolean(string='Is Structured Deal')
    trade_status = fields.Char(string='Trade Status')
    agreement_type_name = fields.Char(string='Agreement Type Name')
    agreement_type_code = fields.Char(string='Agreement Type Code')
    crop_year = fields.Char(string='Crop Year')
    variety = fields.Char(string='Variety')
    contract_type = fields.Char(string='Contract Type')
    is_internal = fields.Boolean(string='Is Internal')
    trade_blotter_process_master_id = fields.Integer(  string='Trade Blotter Process Master ID', index=True)
    asset = fields.Char(string='Asset')
    clearing_broker = fields.Char(string='Clearing Broker')
    cash_broker = fields.Char(string='Cash Broker')
    vehicle = fields.Char(string='Vehicle')
    vehicle_mot_type = fields.Char(string='Vehicle MOT Type')
    line_space = fields.Char(string='Line Space')
    cleared = fields.Char(string='Cleared')
    description = fields.Char(string='Description')
    is_force_majeure = fields.Boolean(string='Is Force Majeure')
    specification_code = fields.Char(string='Specification Code')
    packaging_code = fields.Char(string='Packaging Code')
    license_code = fields.Char(string='License Code')
    mtm_pricing_type = fields.Char(string='MTM Pricing Type')
    qty_periodicity_type = fields.Char(string='Quantity Periodicity Type')
    is_ice_deal = fields.Boolean(string='Is ICE Deal')
    company_agreement_id = fields.Integer(  string='Company Agreement ID', index=True)
    buy_sell = fields.Char(string='Buy Sell')
    bill_to_location = fields.Char(string='Bill To Location')
    location_bs_option = fields.Char(string='Location BS Option')
    is_call_gas = fields.Boolean(string='Is Call Gas')
    remaining_lots = fields.Float(string='Remaining Lots')
    leg_type = fields.Char(string='Leg Type')
    weight_final_at = fields.Char(string='Weight Final At')
    region_location = fields.Char(string='Region Location')
    flow_start_date = fields.Datetime(string='Flow Start Date')
    flow_end_date = fields.Datetime(string='Flow End Date')
    transfer_number = fields.Integer(string='Transfer Number')
    nomination_key = fields.Integer(string='Nomination Key')
    offer_number = fields.Integer(string='Offer Number')
    broker_sub_account = fields.Char(string='Broker Sub Account')
    actual_price = fields.Float(string='Actual Price')
    actual_price_uom = fields.Char(string='Actual Price UOM')
    actual_price_ccy = fields.Char(string='Actual Price Currency')
    ship_to_location = fields.Char(string='Ship To Location')
    quote = fields.Char(string='Quote')
    service_level_enum = fields.Char(string='Service Level Enum')
    pipeline_rate_matrix = fields.Char(string='Pipeline Rate Matrix')
    mtm_curve = fields.Char(string='MTM Curve')
    price = fields.Float(string='Price')
    pricing_term = fields.Char(string='Pricing Term')
    payment_term = fields.Char(string='Payment Term')
    contact_person = fields.Char(string='Contact Person')
    company_agreement_type = fields.Char(string='Company Agreement Type')
    curve_category = fields.Char(string='Curve Category')
    index_type = fields.Char(string='Index Type')
    is_composite = fields.Boolean(string='Is Composite')
    is_mtm_overwrite = fields.Boolean(string='Is MTM Overwrite')
    is_mtm_default = fields.Boolean(string='Is MTM Default')
    is_attachment_available = fields.Boolean(string='Is Attachment Available')
    is_notes_available = fields.Boolean(string='Is Notes Available')
    capacity_quantity = fields.Float(string='Capacity Quantity')
    strategy_l1 = fields.Char(string='Strategy L1')
    strategy_l2 = fields.Char(string='Strategy L2')
    strategy_l3 = fields.Char(string='Strategy L3')
    strategy_l4 = fields.Char(string='Strategy L4')
    strategy_l5 = fields.Char(string='Strategy L5')
    custom_trade_number = fields.Char(string='Custom Trade Number')
    custom_section_number = fields.Char(string='Custom Section Number')
    is_contract_not_required = fields.Boolean(string='Is Contract Not Required')
    cp_term = fields.Char(string='CP Term')
    segment_status = fields.Char(string='Segment Status')
    prompt_date = fields.Datetime(string='Prompt Date')
    parent_link_trade_id = fields.Integer(string='Parent Link Trade ID')
    last_valued_date = fields.Datetime(string='Last Valued Date')
    internal_business_unit = fields.Char(string='Internal Business Unit')
    is_intercompany_pricing = fields.Boolean(string='Is Intercompany Pricing')
    is_invoiced = fields.Boolean(string='Is Invoiced')
    product_code = fields.Char(string='Product Code')
    fx_amount_currency = fields.Char(string='FX Amount Currency')
    product_symbol = fields.Char(string='Product Symbol')
    is_trade_lock = fields.Boolean(string='Is Trade Lock')
    lot_equivalent = fields.Float(string='Lot Equivalent')
    is_term_allocated_to_barge_freight = fields.Boolean(string='Is Term Allocated to Barge Freight')
    schedule_enum = fields.Integer(string='Schedule Enum')
    certificate_no = fields.Char(string='Certificate No')
    inventory_type_display_name = fields.Char(string='Inventory Type DisplayName')
    file_import_id = fields.Integer(string='File Import ID')
    trigger_allocation_method = fields.Char(string='Trigger Allocation Method')
    strike_price = fields.Float(string='Strike Price')
    hs_code = fields.Char(string='HS Code')
    unallocated_link_trade_qty = fields.Float(string='Unallocated Link Trade Quantity')
    delivery_basis_of = fields.Char(string='Delivery Basis Of')
    is_ddp = fields.Boolean(string='Is DDP')
    put_call = fields.Char(string='Put Call')
    underlying_product_code = fields.Char(string='Underlying Product Code')
    ref_physical_id = fields.Integer(string='Ref Physical ID')
    lock_id = fields.Integer(string='Lock ID')
    status_enum = fields.Boolean(string='Status Enum')
    modify_person_id = fields.Integer(string='Modify Person ID')
    modify_person = fields.Char(string='Modify Person')
    last_modify_date = fields.Datetime(string='Last Modify Date')
    customer_id = fields.Integer(string='Customer ID')
    bi_record_creation_date = fields.Datetime(string='BI Record Creation Date')