from odoo import models, fields


class TransferControllerBI(models.Model):
    _name = 'transfer.controller.bi'
    _description = 'Transfer Controller Business Intelligence'

    transfer_controller_bi_id = fields.Integer(string='Transfer Controller BI ID')
    delivery_id = fields.Integer(string='Delivery ID')
    from_type_enum = fields.Char(string='From Type Enum')
    from_type_display_name = fields.Char(string='From Type Display Name')
    from_mot_code = fields.Char(string='From MOT Code')
    from_sub_inventory_code = fields.Char(string='From Sub Inventory Code')
    to_type_enum = fields.Char(string='To Type Enum')
    to_type_display_name = fields.Char(string='To Type Display Name')
    to_mot_code = fields.Char(string='To MOT Code')
    to_sub_inventory_code = fields.Char(string='To Sub Inventory Code')
    location_code = fields.Char(string='Location Code')
    delivery_price = fields.Float(string='Delivery Price')
    delivery_commencement_date = fields.Datetime(string='Delivery Commencement Date')
    delivery_completion_date = fields.Datetime(string='Delivery Completion Date')
    delivery_at_enum = fields.Char(string='Delivery At Enum')
    delivery_at_display_name = fields.Char(string='Delivery At Display Name')
    delivery_status_enum = fields.Char(string='Delivery Status Enum')
    finalized_date = fields.Datetime(string='Finalized Date')
    venture_code = fields.Char(string='Venture Code')
    has_attachment_display_name = fields.Char(string='Has Attachment Display Name')
    operator_person_code = fields.Char(string='Operator Person Code')
    bl_id_code = fields.Char(string='BL ID Code')
    bl_date = fields.Datetime(string='BL Date')
    delivery_active_status_enum = fields.Char(string='Delivery Active Status Enum')
    delivery_active_status_display_name = fields.Char(string='Delivery Active Status Display Name')
    mot_type_enum = fields.Char(string='MOT Type Enum')
    mot_type_display_name = fields.Char(string='MOT Type Display Name')
    delivery_location_code = fields.Char(string='Delivery Location Code')
    inventory_id = fields.Integer(string='Inventory ID')
    delivery_date = fields.Datetime(string='Delivery Date')
    from_strategy_code = fields.Char(string='From Strategy Code')
    to_strategy_code = fields.Char(string='To Strategy Code')
    segment_id = fields.Integer(string='Segment ID')
    from_grade_code = fields.Char(string='From Grade Code')
    to_grade_code = fields.Char(string='To Grade Code')
    title_delivery_date = fields.Datetime(string='Title Delivery Date')
    delivery_reference = fields.Char(string='Delivery Reference')
    trailer_id = fields.Char(string='Trailer ID')
    shape_code = fields.Char(string='Shape Code')
    package_count = fields.Integer(string='Package Count')
    consignee_counterpart_code = fields.Char(string='Consignee Counterpart Code')
    from_segment_section_code = fields.Char(string='From Segment Section Code')
    from_location_code = fields.Char(string='From Location Code')
    from_counterpart_code = fields.Char(string='From Counterpart Code')
    to_segment_section_code = fields.Char(string='To Segment Section Code')
    to_location_code = fields.Char(string='To Location Code')
    to_counterpart_code = fields.Char(string='To Counterpart Code')
    concentrate_display_name = fields.Char(string='Concentrate Display Name')
    itinerary_id = fields.Integer(string='Itinerary ID')
    from_trade_status_enum = fields.Char(string='From Trade Status Enum')
    to_trade_status_enum = fields.Char(string='To Trade Status Enum')
    to_segment_id = fields.Integer(string='To Segment ID')
    from_segment_id = fields.Integer(string='From Segment ID')
    from_material_code = fields.Char(string='From Material Code')
    to_material_code = fields.Char(string='To Material Code')
    from_commodity_code = fields.Char(string='From Commodity Code')
    to_commodity_code = fields.Char(string='To Commodity Code')
    from_asset_code = fields.Char(string='From Asset Code')
    to_asset_code = fields.Char(string='To Asset Code')
    from_origin_code = fields.Char(string='From Origin Code')
    to_origin_code = fields.Char(string='To Origin Code')
    from_brand_code = fields.Char(string='From Brand Code')
    to_brand_code = fields.Char(string='To Brand Code')
    from_shape_code = fields.Char(string='From Shape Code')
    to_shape_code = fields.Char(string='To Shape Code')
    from_actual_qty = fields.Float(string='From Actual Quantity')
    to_actual_qty = fields.Float(string='To Actual Quantity')
    from_actual_qty_uom_code = fields.Char(string='From Actual Quantity UOM Code')
    to_actual_qty_uom_code = fields.Char(string='To Actual Quantity UOM Code')
    from_scheduled_qty = fields.Float(string='From Scheduled Quantity')
    to_scheduled_qty = fields.Float(string='To Scheduled Quantity')
    from_scheduled_qty_uom_code = fields.Char(string='From Scheduled Quantity UOM Code')
    to_scheduled_qty_uom_code = fields.Char(string='To Scheduled Quantity UOM Code')
    from_contract_qty = fields.Float(string='From Contract Quantity')
    from_contract_qty_uom_code = fields.Char(string='From Contract Quantity UOM Code')
    from_open_qty = fields.Float(string='From Open Quantity')
    to_open_qty = fields.Float(string='To Open Quantity')
    from_open_qty_uom_code = fields.Char(string='From Open Quantity UOM Code')
    to_open_qty_uom_code = fields.Char(string='To Open Quantity UOM Code')
    letter_of_credit_code = fields.Char(string='Letter of Credit Code')
    notify_party_code = fields.Char(string='Notify Party Code')
    to_trade_number = fields.Integer(string='To Trade Number')
    from_trade_number = fields.Integer(string='From Trade Number')
    from_physical_master_id = fields.Integer(string='From Physical Master ID')
    from_trade_location_code = fields.Char(string='From Trade Location Code')
    from_trade_load_location_code = fields.Char(string='From Trade Load Location Code')
    from_trade_discharge_location_code = fields.Char(string='From Trade Discharge Location Code')
    limit_breach_display_name = fields.Char(string='Limit Breach Display Name')
    from_schedule_planning_qty = fields.Float(string='From Schedule Planning Quantity')
    from_schedule_planning_qty_uom_code = fields.Char(string='From Schedule Planning Quantity UOM Code')
    from_actual_planning_qty = fields.Float(string='From Actual Planning Quantity')
    from_schedule_shipping_qty = fields.Float(string='From Schedule Shipping Quantity')
    from_schedule_shipping_qty_uom_code = fields.Char(string='From Schedule Shipping Quantity UOM Code')
    from_actual_shipping_qty = fields.Float(string='From Actual Shipping Quantity')
    sap_status_display_name = fields.Char(string='SAP Status Display Name')
    delivery_type_enum = fields.Char(string='Delivery Type Enum')
    delivery_type_display_name = fields.Char(string='Delivery Type Display Name')
    is_inter_company = fields.Boolean(string='Is Inter Company')
    registration_number = fields.Char(string='Registration Number')
    delivery_reference_2 = fields.Char(string='Delivery Reference 2')
    delivery_reference_3 = fields.Char(string='Delivery Reference 3')
    delivery_reference_4 = fields.Char(string='Delivery Reference 4')
    delivery_reference_5 = fields.Char(string='Delivery Reference 5')
    delivery_term_code = fields.Char(string='Delivery Term Code')
    load_location_code = fields.Char(string='Load Location Code')
    discharge_location_code = fields.Char(string='Discharge Location Code')
    final_destination_location_code = fields.Char(string='Final Destination Location Code')
    driver_name = fields.Char(string='Driver Name')
    price_currency_code = fields.Char(string='Price Currency Code')
    price_uom_code = fields.Char(string='Price UOM Code')
    bill_of_lading = fields.Datetime(string='Bill of Lading')
    lclp_start = fields.Datetime(string='LCLP Start')
    lclp_end = fields.Datetime(string='LCLP End')
    lp_nor_berthing = fields.Datetime(string='LP NOR Berthing')
    lp_berthing_date_etd = fields.Datetime(string='LP Berthing Date ETD')
    lp_arrival = fields.Datetime(string='LP Arrival')
    lp_departure = fields.Datetime(string='LP Departure')
    dp_nor = fields.Datetime(string='DP NOR')
    dp_berthing = fields.Datetime(string='DP Berthing')
    dp_arrival = fields.Datetime(string='DP Arrival')
    dp_departure = fields.Datetime(string='DP Departure')
    from_internal_company = fields.Char(string='From Internal Company')
    to_internal_company = fields.Char(string='To Internal Company')
    in_dispute = fields.Boolean(string='In Dispute')
    ts_from_type_enum = fields.Char(string='TS From Type Enum')
    ts_from_type_display_name = fields.Char(string='TS From Type Display Name')
    ts_to_type_enum = fields.Char(string='TS To Type Enum')
    ts_to_type_display_name = fields.Char(string='TS To Type Display Name')
    from_invoice_qty = fields.Float(string='From Invoice Quantity')
    from_invoice_qty_uom = fields.Char(string='From Invoice Quantity UOM')
    to_invoice_qty_uom = fields.Char(string='To Invoice Quantity UOM')
    to_invoice_qty = fields.Float(string='To Invoice Quantity')
    ref_delivery_id = fields.Integer(string='Ref Delivery ID')
    storage_type_enum = fields.Char(string='Storage Type Enum')
    storage_type_display_name = fields.Char(string='Storage Type Display Name')
    incoterm_location_code = fields.Char(string='Incoterm Location Code')
    master_deal_id = fields.Integer(string='Master Deal ID')
    reference_number = fields.Char(string='Reference Number')
    is_folio_account_number = fields.Boolean(string='Is Folio Account Number')
    folio_account_number = fields.Char(string='Folio Account Number')
    nomination_key = fields.Integer(string='Nomination Key')
    packaging_class = fields.Char(string='Packaging Class')
    packaging_group = fields.Char(string='Packaging Group')
    internal_reference = fields.Char(string='Internal Reference')
    internal_reference1 = fields.Char(string='Internal Reference 1')
    inventory_type_display_name = fields.Char(string='Inventory Type Display Name')
    business_unit_code = fields.Char(string='Business Unit Code')
    transport_carriage_code = fields.Char(string='Transport Carriage Code')
    trade_admin_code = fields.Char(string='Trade Admin Code')
    event_date_column1 = fields.Datetime(string='Event Date Column 1')
    event_date_column2 = fields.Datetime(string='Event Date Column 2')
    event_date_column3 = fields.Datetime(string='Event Date Column 3')
    event_date_column4 = fields.Datetime(string='Event Date Column 4')
    event_date_column5 = fields.Datetime(string='Event Date Column 5')
    event_date_column6 = fields.Datetime(string='Event Date Column 6')
    event_date_column7 = fields.Datetime(string='Event Date Column 7')
    event_date_column8 = fields.Datetime(string='Event Date Column 8')
    event_date_column9 = fields.Datetime(string='Event Date Column 9')
    event_date_column10 = fields.Datetime(string='Event Date Column 10')
    from_crop_year_code = fields.Char(string='From Crop Year Code')
    to_crop_year_code = fields.Char(string='To Crop Year Code')
    from_variety_code = fields.Char(string='From Variety Code')
    to_variety_code = fields.Char(string='To Variety Code')
    is_finalized = fields.Boolean(string='Is Finalized')
    vehicle_code = fields.Char(string='Vehicle Code')
    price_entry_type_enum = fields.Char(string='Price Entry Type Enum')
    price_entry_type_display_name = fields.Char(string='Price Entry Type Display Name')
    vehicle_mot_type_enum = fields.Char(string='Vehicle MOT Type Enum')
    vehicle_mot_type_display_name = fields.Char(string='Vehicle MOT Type Display Name')
    commencement_date = fields.Datetime(string='Commencement Date')
    completion_date = fields.Datetime(string='Completion Date')
    goods_return_delete_date = fields.Datetime(string='Goods Return Delete Date')
    goods_return_description = fields.Char(string='Goods Return Description')
    carrier = fields.Char(string='Carrier')
    truck_driver_id = fields.Char(string='Truck Driver ID')
    stock_hold_no = fields.Char(string='Stock Hold No')
    customer_no = fields.Char(string='Customer No')
    account_no = fields.Char(string='Account No')
    consignee = fields.Char(string='Consignee')
    trailer = fields.Char(string='Trailer')
    temperature = fields.Char(string='Temperature')
    gravity_density = fields.Char(string='Gravity Density')
    is_sanction = fields.Boolean(string='Is Sanction')
    description = fields.Char(string='Description')
    deal_classification_enum = fields.Char(string='Deal Classification Enum')
    deal_classification_display_name = fields.Char(string='Deal Classification Display Name')
    product_code = fields.Char(string='Product Code')
    carrier_fein = fields.Char(string='Carrier FEIN')
    bill_to_location = fields.Char(string='Bill To Location')
    transfer_creation_date = fields.Datetime(string='Transfer Creation Date')
    delivery_grade_code = fields.Char(string='Delivery Grade Code')
    weight_final_at_display_text = fields.Char(string='Weight Final At Display Text')
    ship_to_location_code = fields.Char(string='Ship To Location Code')
    from_custom_trade_number = fields.Char(string='From Custom Trade Number')
    custom_section_number = fields.Char(string='Custom Section Number')
    book = fields.Char(string='Book')
    from_book_code = fields.Char(string='From Book Code')
    to_book_code = fields.Char(string='To Book Code')
    nomination_group = fields.Char(string='Nomination Group')
    last_valued_date = fields.Char(string='Last Valued Date')
    is_ticket_present = fields.Boolean(string='Is Ticket Present')
    contract_type_code = fields.Char(string='Contract Type Code')
    certificate_no = fields.Char(string='Certificate No')
    exchange_contract_entry_code = fields.Char(string='Exchange Contract Entry Code')
    to_exchange_contract_entry_code = fields.Char(string='To Exchange Contract Entry Code')
    from_exchange_contract_entry_code = fields.Char(string='From Exchange Contract Entry Code')
    is_transfer_imported = fields.Boolean(string='Is Transfer Imported')
    buy_sell_display_text = fields.Char(string='Buy Sell Display Text')
    portfolio_code = fields.Char(string='Portfolio Code')
    to_is_transit = fields.Boolean(string='To Is Transit')
    period_type_enum_display_text = fields.Char(string='Period Type Enum Display Text')
    from_is_transit = fields.Boolean(string='From Is Transit')
    to_portfolio_code = fields.Char(string='To Portfolio Code')
    from_buy_sell_display_text = fields.Char(string='From Buy Sell Display Text')
    to_buy_sell_display_text = fields.Char(string='To Buy Sell Display Text')
    delivery_basis_of_display_text = fields.Char(string='Delivery Basis of Display Text')
    agent_name = fields.Char(string='Agent Name')
    custom_trade_number = fields.Char(string='Custom Trade Number')
    grade_code = fields.Char(string='Grade Code')
    material_code = fields.Char(string='Material Code')
    origin_code = fields.Char(string='Origin Code')
    trade_link_id = fields.Char(string='Trade Link ID')
    status_enum = fields.Boolean(string='Status Enum')
    modify_person_id = fields.Integer(string='Modify Person ID')
    last_modify_date = fields.Datetime(string='Last Modify Date')
    modify_person = fields.Char(string='Modify Person')
    customer_id = fields.Integer(string='Customer ID')
    lock_id = fields.Integer(string='Lock ID')
    bi_record_creation_date = fields.Datetime(string='BI Record Creation Date')
    Id = fields.Integer("Identity")