from odoo import models, fields
import requests
import logging
import datetime

_logger = logging.getLogger(__name__)

class TransferControllerBI(models.Model):
    _name = 'transfer.controller.bi'
    _description = 'Transfer Controller Business Intelligence'
    
    transfercontrollerbiid = fields.Integer(string="TransferControllerBiId")
    deliveryid = fields.Char(string="DeliveryId")
    fromtypeenum = fields.Char(string="FromTypeEnum")
    fromtypedisplayname = fields.Char(string="FromTypeDisplayName")
    frommotcode = fields.Char(string="FromMotCode")
    fromsubinventorycode = fields.Char(string="FromSubInventoryCode")
    totypeenum = fields.Char(string="ToTypeEnum")
    totypedisplayname = fields.Char(string="ToTypeDisplayName")
    tomotcode = fields.Char(string="ToMotCode")
    tosubinventorycode = fields.Char(string="ToSubInventoryCode")
    locationcode = fields.Char(string="LocationCode")
    deliveryprice = fields.Char(string="DeliveryPrice")
    deliverycommencementdate = fields.Char(string="DeliveryCommencementDate")
    deliverycompletiondate = fields.Char(string="DeliveryCompletionDate")
    deliveryatenum = fields.Char(string="DeliveryAtEnum")
    deliveryatdisplayname = fields.Char(string="DeliveryAtDisplayName")
    deliverystatusenum = fields.Char(string="DeliveryStatusEnum")
    finalizeddate = fields.Char(string="FinalizedDate")
    venturecode = fields.Char(string="VentureCode")
    hasattachmentdisplayname = fields.Char(string="HasAttachmentDisplayName")
    operatorpersoncode = fields.Char(string="OperatorPersonCode")
    blidcode = fields.Char(string="BlIdCode")
    bldate = fields.Char(string="BlDate")
    deliveryactivestatusenum = fields.Char(string="DeliveryActiveStatusEnum")
    deliveryactivestatusdisplayname = fields.Char(string="DeliveryActiveStatusDisplayName")
    mottypeenum = fields.Char(string="MotTypeEnum")
    mottypedisplayname = fields.Char(string="MotTypeDisplayName")
    deliverylocationcode = fields.Char(string="DeliveryLocationCode")
    inventoryid = fields.Char(string="InventoryId")
    deliverydate = fields.Char(string="DeliveryDate")
    fromstrategycode = fields.Char(string="FromStrategyCode")
    tostrategycode = fields.Char(string="ToStrategyCode")
    segmentid = fields.Char(string="SegmentId")
    fromgradecode = fields.Char(string="FromGradeCode")
    togradecode = fields.Char(string="ToGradeCode")
    titledeliverydate = fields.Char(string="TitleDeliveryDate")
    deliveryreference = fields.Char(string="DeliveryReference")
    trailerid = fields.Char(string="TrailerId")
    shapecode = fields.Char(string="ShapeCode")
    packagecount = fields.Char(string="PackageCount")
    consigneecounterpartcode = fields.Char(string="ConsigneeCounterpartCode")
    fromsegmentsectioncode = fields.Char(string="FromSegmentSectionCode")
    fromlocationcode = fields.Char(string="FromLocationCode")
    fromcounterpartcode = fields.Char(string="FromCounterpartCode")
    tosegmentsectioncode = fields.Char(string="ToSegmentSectionCode")
    tolocationcode = fields.Char(string="ToLocationCode")
    tocounterpartcode = fields.Char(string="ToCounterpartCode")
    concentratedisplayname = fields.Char(string="ConcentrateDisplayName")
    itineraryid = fields.Char(string="ItineraryId")
    fromtradestatusenum = fields.Char(string="FromTradeStatusEnum")
    totradestatusenum = fields.Char(string="ToTradeStatusEnum")
    tosegmentid = fields.Char(string="ToSegmentId")
    fromsegmentid = fields.Char(string="FromSegmentId")
    frommaterialcode = fields.Char(string="FromMaterialCode")
    tomaterialcode = fields.Char(string="ToMaterialCode")
    fromcommoditycode = fields.Char(string="FromCommodityCode")
    tocommoditycode = fields.Char(string="ToCommodityCode")
    fromassetcode = fields.Char(string="FromAssetCode")
    toassetcode = fields.Char(string="ToAssetCode")
    fromorigincode = fields.Char(string="FromOriginCode")
    toorigincode = fields.Char(string="ToOriginCode")
    frombrandcode = fields.Char(string="FromBrandCode")
    tobrandcode = fields.Char(string="ToBrandCode")
    fromshapecode = fields.Char(string="FromShapeCode")
    toshapecode = fields.Char(string="ToShapeCode")
    fromactualqty = fields.Char(string="FromActualQty")
    toactualqty = fields.Char(string="ToActualQty")
    fromactualqtyuomcode = fields.Char(string="FromActualQtyUomCode")
    toactualqtyuomcode = fields.Char(string="ToActualQtyUomCode")
    fromscheduledqty = fields.Char(string="FromScheduledQty")
    toscheduledqty = fields.Char(string="ToScheduledQty")
    fromscheduledqtyuomcode = fields.Char(string="FromScheduledQtyUomCode")
    toscheduledqtyuomcode = fields.Char(string="ToScheduledQtyUomCode")
    fromcontractqty = fields.Char(string="FromContractQty")
    fromcontractqtyuomcode = fields.Char(string="FromContractQtyUomCode")
    fromopenqty = fields.Char(string="FromOpenQty")
    toopenqty = fields.Char(string="ToOpenQty")
    fromopenqtyuomcode = fields.Char(string="FromOpenQtyUomCode")
    toopenqtyuomcode = fields.Char(string="ToOpenQtyUomCode")
    letterofcreditcode = fields.Char(string="LetterOfCreditCode")
    notifypartycode = fields.Char(string="NotifyPartyCode")
    totradenumber = fields.Char(string="ToTradeNumber")
    fromtradenumber = fields.Char(string="FromTradeNumber")
    fromphysicalmasterid = fields.Char(string="FromPhysicalMasterId")
    fromtradelocationcode = fields.Char(string="FromTradeLocationCode")
    fromtradeloadlocationcode = fields.Char(string="FromTradeLoadLocationCode")
    fromtradedischargelocationcode = fields.Char(string="FromTradeDischargeLocationCode")
    limitbreachdisplayname = fields.Char(string="LimitBreachDisplayName")
    fromscheduleplanningqty = fields.Char(string="FromSchedulePlanningQty")
    fromscheduleplanningqtyuomcode = fields.Char(string="FromSchedulePlanningQtyUomCode")
    fromactualplanningqty = fields.Char(string="FromActualPlanningQty")
    fromscheduleshippingqty = fields.Char(string="FromScheduleShippingQty")
    fromscheduleshippingqtyuomcode = fields.Char(string="FromScheduleShippingQtyUomCode")
    fromactualshippingqty = fields.Char(string="FromActualShippingQty")
    sapstatusdisplayname = fields.Char(string="SapStatusDisplayName")
    deliverytypeenum = fields.Char(string="DeliveryTypeEnum")
    deliverytypedisplayname = fields.Char(string="DeliveryTypeDisplayName")
    isintercompany = fields.Char(string="IsInterCompany")
    registrationnumber = fields.Char(string="RegistrationNumber")
    deliveryreference2 = fields.Char(string="DeliveryReference2")
    deliveryreference3 = fields.Char(string="DeliveryReference3")
    deliveryreference4 = fields.Char(string="DeliveryReference4")
    deliveryreference5 = fields.Char(string="DeliveryReference5")
    deliverytermcode = fields.Char(string="DeliveryTermCode")
    loadlocationcode = fields.Char(string="LoadLocationCode")
    dischargelocationcode = fields.Char(string="DischargeLocationCode")
    finaldestinationlocationcode = fields.Char(string="FinalDestinationLocationCode")
    drivername = fields.Char(string="DriverName")
    pricecurrencycode = fields.Char(string="PriceCurrencyCode")
    priceuomcode = fields.Char(string="PriceUomCode")
    billoflading = fields.Char(string="BillOfLading")
    lclpstart = fields.Char(string="LclpStart")
    lclpend = fields.Char(string="LclpEnd")
    lpnorberthing = fields.Char(string="LpNorBerthing")
    lpberthingdateetd = fields.Char(string="LpBerthingDateEtd")
    lparrival = fields.Char(string="LpArrival")
    lpdeparture = fields.Char(string="LpDeparture")
    dpnor = fields.Char(string="DpNor")
    dpberthing = fields.Char(string="DpBerthing")
    dparrival = fields.Char(string="DpArrival")
    dpdeparture = fields.Char(string="DpDeparture")
    frominternalcompany = fields.Char(string="FromInternalCompany")
    tointernalcompany = fields.Char(string="ToInternalCompany")
    indispute = fields.Char(string="InDispute")
    tsfromtypeenum = fields.Char(string="TsFromTypeEnum")
    tsfromtypedisplayname = fields.Char(string="TsFromTypeDisplayName")
    tstotypeenum = fields.Char(string="TsToTypeEnum")
    tstotypedisplayname = fields.Char(string="TsToTypeDisplayName")
    frominvoiceqty = fields.Char(string="FromInvoiceQty")
    frominvoiceqtyuom = fields.Char(string="FromInvoiceQtyUom")
    toinvoiceqtyuom = fields.Char(string="ToInvoiceQtyUom")
    toinvoiceqty = fields.Char(string="ToInvoiceQty")
    refdeliveryid = fields.Char(string="RefDeliveryId")
    storagetypeenum = fields.Char(string="StorageTypeEnum")
    storagetypedisplayname = fields.Char(string="StorageTypeDisplayName")
    incotermlocationcode = fields.Char(string="IncotermLocationCode")
    masterdealid = fields.Char(string="MasterDealId")
    referencenumber = fields.Char(string="ReferenceNumber")
    isfolioaccountnumber = fields.Char(string="IsFolioAccountNumber")
    folioaccountnumber = fields.Char(string="FolioAccountNumber")
    nominationkey = fields.Char(string="NominationKey")
    packagingclass = fields.Char(string="PackagingClass")
    packaginggroup = fields.Char(string="PackagingGroup")
    internalreference = fields.Char(string="InternalReference")
    internalreference1 = fields.Char(string="InternalReference1")
    inventorytypedisplayname = fields.Char(string="InventoryTypeDisplayName")
    businessunitcode = fields.Char(string="BusinessUnitCode")
    transportcarriagecode = fields.Char(string="TransportCarriageCode")
    tradeadmincode = fields.Char(string="TradeAdminCode")
    eventdatecolumn1 = fields.Char(string="EventDateColumn1")
    eventdatecolumn2 = fields.Char(string="EventDateColumn2")
    eventdatecolumn3 = fields.Char(string="EventDateColumn3")
    eventdatecolumn4 = fields.Char(string="EventDateColumn4")
    eventdatecolumn5 = fields.Char(string="EventDateColumn5")
    eventdatecolumn6 = fields.Char(string="EventDateColumn6")
    eventdatecolumn7 = fields.Char(string="EventDateColumn7")
    eventdatecolumn8 = fields.Char(string="EventDateColumn8")
    eventdatecolumn9 = fields.Char(string="EventDateColumn9")
    eventdatecolumn10 = fields.Char(string="EventDateColumn10")
    fromcropyearcode = fields.Char(string="FromCropYearCode")
    tocropyearcode = fields.Char(string="ToCropYearCode")
    fromvarietycode = fields.Char(string="FromVarietyCode")
    tovarietycode = fields.Char(string="ToVarietyCode")
    isfinalized = fields.Char(string="IsFinalized")
    vehiclecode = fields.Char(string="VehicleCode")
    priceentrytypeenum = fields.Char(string="PriceEntryTypeEnum")
    priceentrytypedisplayname = fields.Char(string="PriceEntryTypeDisplayName")
    vehiclemottypeenum = fields.Char(string="VehicleMotTypeEnum")
    vehiclemottypedisplayname = fields.Char(string="VehicleMotTypeDisplayName")
    commencementdate = fields.Char(string="CommencementDate")
    completiondate = fields.Char(string="CompletionDate")
    goodsreturndeletedate = fields.Char(string="GoodsReturnDeleteDate")
    goodsreturndescription = fields.Char(string="GoodsReturnDescription")
    carrier = fields.Char(string="Carrier")
    truckdriverid = fields.Char(string="TruckDriverId")
    stockholdno = fields.Char(string="StockHoldNo")
    customerno = fields.Char(string="CustomerNo")
    accountno = fields.Char(string="AccountNo")
    consignee = fields.Char(string="Consignee")
    trailer = fields.Char(string="Trailer")
    temperature = fields.Char(string="Temperature")
    gravitydensity = fields.Char(string="GravityDensity")
    issanction = fields.Char(string="IsSanction")
    description = fields.Char(string="Description")
    dealclassificationenum = fields.Char(string="DealClassificationEnum")
    dealclassificationdisplayname = fields.Char(string="DealClassificationDisplayName")
    productcode = fields.Char(string="ProductCode")
    carrierfein = fields.Char(string="CarrierFein")
    billtolocation = fields.Char(string="BillToLocation")
    transfercreationdate = fields.Char(string="TransferCreationDate")
    deliverygradecode = fields.Char(string="DeliveryGradeCode")
    weightfinalatdisplaytext = fields.Char(string="WeightFinalAtDisplayText")
    shiptolocationcode = fields.Char(string="ShipToLocationCode")
    fromcustomtradenumber = fields.Char(string="FromCustomTradeNumber")
    customsectionnumber = fields.Char(string="CustomSectionNumber")
    book = fields.Char(string="Book")
    frombookcode = fields.Char(string="FromBookCode")
    tobookcode = fields.Char(string="ToBookCode")
    nominationgroup = fields.Char(string="NominationGroup")
    lastvalueddate = fields.Char(string="LastValuedDate")
    isticketpresent = fields.Char(string="IsTicketPresent")
    operator = fields.Char(string="Operator")
    contracttypecode = fields.Char(string="ContractTypeCode")
    certificateno = fields.Char(string="CertificateNo")
    exchangecontractentrycode = fields.Char(string="ExchangeContractEntryCode")
    toexchangecontractentrycode = fields.Char(string="ToExchangeContractEntryCode")
    fromexchangecontractentrycode = fields.Char(string="FromExchangeContractEntryCode")
    istransferimported = fields.Char(string="IsTransferImported")
    buyselldisplaytext = fields.Char(string="BuySellDisplayText")
    portfoliocode = fields.Char(string="PortfolioCode")
    toistransit = fields.Char(string="ToIsTransit")
    periodtypeenumdisplaytext = fields.Char(string="PeriodTypeEnumDisplayText")
    fromistransit = fields.Char(string="FromIsTransit")
    toportfoliocode = fields.Char(string="ToPortfolioCode")
    frombuyselldisplaytext = fields.Char(string="FromBuySellDisplayText")
    tobuyselldisplaytext = fields.Char(string="ToBuySellDisplayText")
    deliverybasisofdisplaytext = fields.Char(string="DeliveryBasisOfDisplayText")
    agentname = fields.Char(string="AgentName")
    customtradenumber = fields.Char(string="CustomTradeNumber")
    gradecode = fields.Char(string="GradeCode")
    materialcode = fields.Char(string="MaterialCode")
    origincode = fields.Char(string="OriginCode")
    tradelinkid = fields.Char(string="TradeLinkId")
    statusenum = fields.Char(string="StatusEnum")
    modifypersonid = fields.Char(string="ModifyPersonId")
    lastmodifydate = fields.Char(string="LastModifyDate")
    modifyperson = fields.Char(string="ModifyPerson")
    customerid = fields.Char(string="CustomerId")
    lockid = fields.Char(string="LockId")
    birecordcreationdate = fields.Char(string="BiRecordCreationDate")
    
    def import_transfer(self):
        interface = self.env['fusion.sync.history']
        last_sync = '2023-01-01'
        url = "https://fusionsqlmirrorapi.azure-api.net/api/transfer"
        headers = {
            'Ocp-Apim-Subscription-Key': '38cb5797102f4b1f852ae8ff6e8482e5',
            'Content-Type': 'application/json',
        }
        params = {
            'date': last_sync
        }
        
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            try:
                json_data = response.json()
                json_data = interface.lowercase_keys(json_data)
                for data in json_data:
                    self.create_update_transfer('transfer', data)
                interface.update_sync_interface('transfer')
            except Exception as e:
                _logger.error('Error processing API data: %s', str(e))
        else:
            _logger.error('Failed to fetch data from external API: %s', response.status_code)
    
    def sync_transfer(self):
        interface = self.env['fusion.sync.history']
        last_sync = interface.get_last_sync('transfer')
        url = "https://fusionsqlmirrorapi.azure-api.net/api/transfer"
        headers = {
            'Ocp-Apim-Subscription-Key': '38cb5797102f4b1f852ae8ff6e8482e5',
            'Content-Type': 'application/json',
        }
        params = {
            'date': last_sync
        }
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            try:
                json_data = response.json()
                json_data = interface.lowercase_keys(json_data)
                for data in json_data:
                    self.regular_update_transfer('transfer', data)
                interface.update_sync_interface('transfer')
            except Exception as e:
                _logger.error('Error processing API data: %s', str(e))
        else:
            _logger.error('Failed to fetch data from external API: %s', response.status_code)
    
    def create_update_transfer(self, interface_type, data):
        if interface_type == 'transfer':
            exists = self.env['transfer.controller.bi'].search([('transfercontrollerbiid', '=', data['transfercontrollerbiid'])])
            if exists:
                return
                # if exists:
                #     return
                # else:
                #     self.env['cashflow.controller.bi'].search([('cashflowid', '=', data['cashflowid'])]).unlink()
                #     self.env['cashflow.controller.bi'].create(data)
                #     self.env.cr.commit()
            else:
                self.env['transfer.controller.bi'].create(data)
                self.env.cr.commit()
    
    def regular_update_transfer(self, interface_type, data):
        if interface_type == 'transfer':
            exists = self.env['transfer.controller.bi'].search([('transfercontrollerbiid', '=', data['transfercontrollerbiid'])])
            if exists:
                self.env['transfer.controller.bi'].search([('transfercontrollerbiid', '=', data['transfercontrollerbiid'])]).unlink()
                self.env['transfer.controller.bi'].create(data)
            else:
                self.env['transfer.controller.bi'].create(data)
                self.env.cr.commit()