from . import account_move
from . import sale_order
from . import stock_picking
from . import trucktransportdetails
from . import res_partner_bank
from . import payment_term_text
from . import vessel
from . import vessel_information
from . import purchase_order
from . import stock_move
